[project]
name = "prefect"
version = "0.1.0"
description = "Espartina's Prefect workflows"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "prefect",
]

[tool.uv.sources]
prefect = { workspace = true }
